spring.application.name=ors
server.port=8080
spring.datasource.url=jdbc:mysql://172.17.0.2:3306/ors
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
cors.allowed.origins=http://3.83.31.179:3000
