spring.application.name=ors
server.port=8080
<<<<<<< HEAD
spring.datasource.url=jdbc:mysql://54.224.84.39:3306/db
=======
spring.datasource.url=jdbc:mysql://172.17.0.2:3306/ors
>>>>>>> 2e3138cbe537f8174a71604cc28dcf18ac210840
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
cors.allowed.origins=http://3.83.31.179:3000
